version: '3'

services:

    mysql-server:
        image:                   mysql:5.7
        hostname:                mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: userpass
        volumes:
            -                    ./db/dumps:/docker-entrypoint-initdb.d
            -                    ./db/data:/var/lib/mysql
        networks:
            -                    daw-network

    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST:            mysql-server
            PMA_PORT:            3306
            MYSQL_ROOT_PASSWORD: userpass
        networks:
            -                    daw-network
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"

    node-backend:
        image:                   abassi/nodejs-server:10.0-dev
        volumes:
            -                    ./src/back:/home/node/app/src
            -                    ./src/front:/home/node/app/static
        networks:
            -                    daw-network
        depends_on:
            -                    mysql-server
        ports: 
            -                    "8000:3000"
        command:                 nodemon /home/node/app/src/index.js

networks:
    daw-network:
        driver:                  bridge